languageCode = "en-us"
title = "Aerial"
baseurl = "http://example.org/"
theme = "aerial"

[params]
  name = "Jaber Zarif"
  about = "Front-End Developer"
  copyright = "Jaber Zarif 2018 - "
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = ""
  favicon = "favicon.ico"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/jaberzarif"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/jaber.zarif.22"
  
[[params.social]]
  medium = "Linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/jaber-zarif-3aa4b8114/"

[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/Jaberzarif"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "jaber.zarif@outlook.fr"
